# Data Preprocessing Tools

## Importing the libraries

### Why We Import These Libraries (Detailed)

- `numpy` enduku?
  Numpy fast ga numbers meeda work chestundi. ML lo data mostly numbers untayi, kabatti calculations fast ga jaragali.
- `pandas` enduku?
  CSV file ni table laga easy ga read cheyyali ante pandas best. Rows, columns select cheyyadam chala easy.
- `matplotlib` enduku?
  I notebook lo direct ga graphs ekkuva use cheyyakapoyina, data ni visual ga chudali ante idi helpful. Real projects lo patterns and outliers chudataniki use avutundi.

Simple ga: tools box lo right tools petti work start chestunnam.

In [ ]:
# Step 1: Numerical calculations kosam numpy library ni import chestunnam.
import numpy as np
# Step 2: Graphs/plots draw cheyyadaniki matplotlib module ni import chestunnam.
import matplotlib.pyplot as plt
# Step 3: Dataset ni read and handle cheyyadaniki pandas library ni import chestunnam.
import pandas as pd

## Importing the dataset

### Why We Load Dataset and Split into X, y

- Dataset load enduku?
  Model ki nerpinchadaniki first data kavali. `Data.csv` ane file lo mana examples untayi.
- `X` (features) and `y` (target) separate enduku?
  ML model logic: **inputs** (X) ivvali, **output** (y) predict cheyyali.
  Example: country, age, salary -> purchased or not.
- Last column ni `y` ga enduku tiskunnam?
  Chala datasets lo final column result/label untundi. Anduke standard ga last column target ga tiskuntam.

Simple ga: question paper (X) and answer key (y) separate chestunnam.

### Features vs Independent vs Dependent Variables

- **Feature ante enti?**
  Feature ante model ki ichhe oka information column.
  Example: Age, Salary, Country.
  Prati column oka clue laanti di.

- **Independent Variables (X) ante enti?**
  Model ni guide cheyyadaniki manam input ga iche anni features ni kalipi `X` antam.
  Dinni predictors/input variables ani kuda antaru.
  Ee values result ni influence chestayi.

- **Dependent Variable (y) ante enti?**
  Manam predict cheyyali anukune final result ni `y` antam.
  Dinni target/output/label ani kuda antaru.
  Idi `X` meeda depend avuthundi, anduke dependent variable.

- **Simple Example (Job Selection style)**
  - Features: Aptitude Score, Communication Score, Experience Years
  - Independent Variables (X): paina 3 columns
  - Dependent Variable (y): Selected (Yes/No)

- **Real Meaning in this notebook**
  - `X = dataset.iloc[:, :-1].values` -> last column kakunda migatha columns anni inputs.
  - `y = dataset.iloc[:, -1].values` -> last column target result.

Simple ga: `X` questions, `y` answer.
Model pani: `X` chusi `y` predict cheyyadam.

In [ ]:
# Step 4: 'Data.csv' file nundi complete dataset ni DataFrame lo load chestunnam.
dataset = pd.read_csv('Data.csv')
# Step 5: Last column ni vadilesi migilina columns anni features (X) ga tiskuntunnam.
X = dataset.iloc[:, :-1].values
# Step 6: Last column ni target/dependent variable (y) ga store chestunnam.
y = dataset.iloc[:, -1].values

In [ ]:
# Step 7: Features matrix (X) current state ni check cheyyadaniki print chestunnam.
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
# Step 8: Target vector (y) values correct ga vachaya ani verify cheyyadaniki print chestunnam.
print(y)

<ArrowStringArray>
['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 10, dtype: str


## Taking care of missing data

### Why We Handle Missing Data

- Missing values problem enti?
  Konni rows lo age/salary empty untayi. Model ki empty value ardham kaadu.
- Mean strategy enduku?
  Numeric columns ki average value reasonable fill. Data pattern ni complete ga spoil cheyyakunda fill chestundi.
- `fit` and `transform` difference enti?
  `fit` = average value nerchukuntundi.
  `transform` = aa average ni missing places lo fill chestundi.
- 1:3 columns enduku?
  Ee dataset structure prakaram missing numeric values aa columns lo unnayi.

Simple ga: notebook lo blank spaces ni sensible words tho fill chesinattu.

In [19]:
# Step 9: Missing values fill cheyyadaniki sklearn nundi SimpleImputer ni import chestunnam.
from sklearn.impute import SimpleImputer as si
# Step 10: NaN values ni mean tho replace cheyyadaniki imputer object create chestunnam.
imputer = si(missing_values=np.nan, strategy='mean')
# Step 11: Column index 1 to 2 data meeda mean values learn cheyyadaniki fit chestunnam.
imputer.fit(X[:, 1:3])
# Step 12: Learned mean values use chesi missing places ni fill chestunnam.
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
# Step 13: Missing data handle ayyaka updated features (X) ni print chesi check chestunnam.
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding Topics in Correct Learning Order

#### 1) What is Category and Categorical Data?
- **Category** ante oka group name or label.
- Example: `France`, `Spain`, `Germany` each one is a category.
- `Yes`, `No` kuda categories.

- **Categorical data** ante text/label form lo unna data.
- Direct ga math cheyyalem, kabatti model ki before processing convert cheyyali.

In our notebook:
1. `Country` column in `X` is categorical (France, Spain, Germany).
2. `Purchased` column in `y` is categorical (Yes, No).

#### 2) Why Encoding is Needed
- ML models mostly numeric calculations chestayi.
- Text values ni model direct ga understand cheyyadu.
- So, text categories ni numbers ga marchadam mandatory.

#### 3) What is One-Hot Encoding?
- One-Hot Encoding ante oka categorical column ni multiple binary (0/1) columns ga split cheyyadam.
- Prati category ki oka separate column untundi.
- Row lo unna category ki `1`, migatha categories ki `0` untayi.

Example (`Country`):
- France -> [1, 0, 0]
- Spain -> [0, 1, 0]
- Germany -> [0, 0, 1]

Why useful?
- Artificial ranking problem avoid avuthundi.
- France=0, Spain=1, Germany=2 ani direct numbers iste model wrong order ni assume cheyyachu.

#### 4) Encoding for Independent Variables (`X`)
- `Country` laanti input categories ki mostly **One-Hot Encoding** use chestam.
- Enduku?
  France=0, Spain=1, Germany=2 ani direct numbers iste model wrong order assume cheyyachu.
- One-hot lo separate columns create avuthayi:
  - France -> [1, 0, 0]
  - Spain -> [0, 1, 0]
  - Germany -> [0, 0, 1]

#### 5) Why `X = np.array(ct.fit_transform(X))`?
- `ct.fit_transform(X)` output numpy-like structure or sparse matrix laga ravachu (encoder settings batti).
- `np.array(...)` valla output ni plain NumPy array format lo stabilize chestam.
- Next preprocessing steps (`train_test_split`, scaling, slicing, printing) consistent ga easy ga work avvadaniki idi help chestundi.
- Simple ga: data ni one standard shape/type lo petti pipeline smooth ga run avvadam kosam.

#### 6) What is LabelEncoder?
- LabelEncoder ane tool text labels ni numeric labels ga convert chestundi.
- Example: `No` -> 0, `Yes` -> 1.
- Idi mostly target/dependent variable (`y`) ki use chestam, especially binary classes unnapudu.

#### 7) Why mostly LabelEncoder is used for dependent variable (`y`)?
- `y` usually final output label kabatti single column lo untundi (Yes/No, Pass/Fail, Spam/Not Spam).
- Ee label ni numeric ga marchadam chalu; class order meaning create cheyyalsina avasaram usually undadu.
- `X` lo categories ki direct 0,1,2 petthe artificial order problem vastundi, kabatti akkada One-Hot safer.
- Example:
  - `y`: Yes/No -> `1/0` (safe)
  - `X` Country: France/Spain/Germany -> 0/1/2 (unsafe), One-Hot better.
- Exception: `X` lo real order unte (Small < Medium < Large), appudu ordinal style encoding use cheyyachu.

#### 8) Encoding for Dependent Variable (`y`)
- `Purchased` laanti target binary values ki **Label Encoding** saripothundi.
- **LabelEncoder enduku use chestam?**
  Model ki final target text (`Yes`/`No`) direct ga ivvakunda numeric labels (`1`/`0`) ga marchadaniki.
- Binary target lo idi simple and correct mapping istundi.
- Example:
  - No -> 0
  - Yes -> 1

#### 9) Quick Rule
1. Input feature category order lekapothe -> One-Hot.
2. Target binary aithe -> Label Encoding enough.
3. Goal: model confusion lekunda clean numeric representation ivvadam.

### Encoding the Independent Variable

In [ ]:
# Step 14: Specific columns ki different transforms apply cheyyadaniki ColumnTransformer ni import chestunnam.
from sklearn.compose import ColumnTransformer
# Step 15: Categorical text ni binary columns ga marchadaniki OneHotEncoder ni import chestunnam.
from sklearn.preprocessing import OneHotEncoder
# Step 16: 0th column ki one-hot encoding apply chesi, migatha columns ni alane pass-through cheyyadaniki transformer set chestunnam.
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# Step 17: Transformer output ni fit-transform chesi, next steps lo stable ga use cheyyadaniki plain NumPy array ga convert chestunnam.
X = np.array(ct.fit_transform(X))

In [20]:
# Step 18: Independent variable encoding tarvata X ela undho print chesi verify chestunnam.
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [ ]:
# Step 19: Target labels ni number format lo ki marchadaniki LabelEncoder ni import chestunnam.
from sklearn.preprocessing import LabelEncoder
# Step 20: Label encoding operation kosam encoder object create chestunnam (text target ni model-friendly numbers ga marchadaniki).
le = LabelEncoder()
# Step 21: y lo unna class names ni integer labels ga convert chestunnam (example: No->0, Yes->1).
y = le.fit_transform(y)

In [ ]:
# Step 22: Dependent variable encoding result ni print chesi confirm chestunnam.
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

### Why We Split into Train and Test

- Train set enduku?
  Model ni nerpinchadaniki.
- Test set enduku?
  Model real ga new data meeda ela perform chestundo check cheyyadaniki.
- `test_size=0.2` enduku?
  80% learning, 20% exam style validation. Common and balanced choice.
- `random_state=1` enduku?
  Same split malli malli ravadaniki (reproducibility). Team lo evaru run chesina same result vastundi.

Simple ga: tuition class (train) and final exam (test) separate chestunnam.

In [ ]:
# Step 23: Dataset ni train and test sets ga split cheyyadaniki function ni import chestunnam.
from sklearn.model_selection import train_test_split
# Step 24: 80% data training ki, 20% data testing ki split chestunnam; random_state fixed kabatti same split repeat avutundi.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
# Step 25: Training features ela unnayo choodadaniki X_train ni print chestunnam.
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
# Step 26: Testing features ela unnayo verify cheyyadaniki X_test ni print chestunnam.
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
# Step 27: Training target labels ni check cheyyadaniki y_train ni print chestunnam.
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
# Step 28: Testing target labels ni check cheyyadaniki y_test ni print chestunnam.
print(y_test)

[0 1]


## Feature Scaling

### Why We Do Feature Scaling

- Scaling problem enti?
  Age 20-50 range lo untundi, salary 30000-90000 range lo untundi. Pedda number column model decision ni dominate cheyyachu.
- StandardScaler enduku?
  Features ni similar scale ki teesukostundi (mean around 0, std around 1).
  Formula concept: z = (x - mean) / std.
- `fit_transform(X_train)` and `transform(X_test)` enduku?
  Train data nundi mathrame mean/std nerchukovali.
  Test data ni ade rules tho transform cheyyali.
  Test data nundi learn chesthe data leakage jaruguthundi.

Simple ga: oka player cm lo, inko player inches lo measure chesthe compare kashtam. First same unit lo ki marchi compare chestunnam.

In [ ]:
# Step 29: Feature values ni same scale lo ki teesukoradaniki StandardScaler ni import chestunnam.
from sklearn.preprocessing import StandardScaler
# Step 30: Scaling operation kosam scaler object create chestunnam.
sc = StandardScaler()
# Step 31: Training data meeda mean and std learn chesi X_train ni scale chestunnam.
X_train = sc.fit_transform(X_train)
# Step 32: Ade learned scaling rules ni X_test ki apply chestunnam (data leakage avoid avuthundi).
X_test = sc.transform(X_test)

In [ ]:
# Step 33: Scaled training features ni print chesi centered values vachaya ani check chestunnam.
print(X_train)

[[-0.77459667 -0.57735027  1.29099445 -0.19159184 -1.07812594]
 [-0.77459667  1.73205081 -0.77459667 -0.01411729 -0.07013168]
 [ 1.29099445 -0.57735027 -0.77459667  0.56670851  0.63356243]
 [-0.77459667 -0.57735027  1.29099445 -0.30453019 -0.30786617]
 [-0.77459667 -0.57735027  1.29099445 -1.90180114 -1.42046362]
 [ 1.29099445 -0.57735027 -0.77459667  1.14753431  1.23265336]
 [-0.77459667  1.73205081 -0.77459667  1.43794721  1.57499104]
 [ 1.29099445 -0.57735027 -0.77459667 -0.74014954 -0.56461943]]


In [ ]:
# Step 34: Scaled testing features ni print chesi final preprocessing output ni verify chestunnam.
print(X_test)

[[-0.77459667  1.73205081 -0.77459667 -1.46618179 -0.9069571 ]
 [ 1.29099445 -0.57735027 -0.77459667 -0.44973664  0.20564034]]


## Kid-Style Architecture and Flow (Data Preprocessing)

Manam ikada raw data ni clean chesi, machine learning ki ready chestunnam.
Simple ga idi "school ki velladaniki child ni ready cheyyadam" laanti process.

### End-to-End Flow

```mermaid
flowchart TD
    A[Raw CSV Data] --> B[Load into Pandas]
    B --> C[Split X and y]
    C --> D[Handle Missing Values]
    D --> E[Encode Categorical Values]
    E --> F[Train Test Split]
    F --> G[Feature Scaling]
    G --> H[Clean ML Ready Data]
```

### Architecture Simple Explanation
1. **Input Layer**: `Data.csv` nundi raw data vasthundi.
2. **Cleaning Layer**: missing values fill chestham.
3. **Encoding Layer**: text values ni numbers ga marchestham.
4. **Split Layer**: train set and test set create chestham.
5. **Scaling Layer**: feature values same scale lo ki teesukostham.
6. **Output Layer**: model training ki ready data.

### Kid Analogy
- Raw data = unwashed vegetables
- Cleaning = wash + cut
- Encoding = labels pettadam
- Split = practice vs exam papers
- Scaling = all rulers ni same unit lo set cheyyadam