# Data Preprocessing Tools

## Importing the libraries

### Why We Import These Libraries (Detailed)

- `numpy` enduku?
  Numpy fast ga numbers meeda work chestundi. ML lo data mostly numbers untayi, kabatti calculations fast ga jaragali.
- `pandas` enduku?
  CSV file ni table laga easy ga read cheyyali ante pandas best. Rows, columns select cheyyadam chala easy.
- `matplotlib` enduku?
  I notebook lo direct ga graphs ekkuva use cheyyakapoyina, data ni visual ga chudali ante idi helpful. Real projects lo patterns and outliers chudataniki use avutundi.

Simple ga: tools box lo right tools petti work start chestunnam.

In [37]:
# Step 1: Numerical calculations kosam numpy library ni import chestunnam.
import numpy as np
# Step 2: Graphs/plots draw cheyyadaniki matplotlib module ni import chestunnam.
import matplotlib.pyplot as plt
# Step 3: Dataset ni read and handle cheyyadaniki pandas library ni import chestunnam.
import pandas as pd

## Importing the dataset

### Why We Load Dataset and Split into X, y

- Dataset load enduku?
  Model ki nerpinchadaniki first data kavali. `Data.csv` ane file lo mana examples untayi.
- `X` (features) and `y` (target) separate enduku?
  ML model logic: **inputs** (X) ivvali, **output** (y) predict cheyyali.
  Example: country, age, salary -> purchased or not.
- Last column ni `y` ga enduku tiskunnam?
  Chala datasets lo final column result/label untundi. Anduke standard ga last column target ga tiskuntam.

Simple ga: question paper (X) and answer key (y) separate chestunnam.

### Features vs Independent vs Dependent Variables

- **Feature ante enti?**
  Feature ante model ki ichhe oka information column.
  Example: Age, Salary, Country.
  Prati column oka clue laanti di.

- **Independent Variables (X) ante enti?**
  Model ni guide cheyyadaniki manam input ga iche anni features ni kalipi `X` antam.
  Dinni predictors/input variables ani kuda antaru.
  Ee values result ni influence chestayi.

- **Dependent Variable (y) ante enti?**
  Manam predict cheyyali anukune final result ni `y` antam.
  Dinni target/output/label ani kuda antaru.
  Idi `X` meeda depend avuthundi, anduke dependent variable.

- **Simple Example (Job Selection style)**
  - Features: Aptitude Score, Communication Score, Experience Years
  - Independent Variables (X): paina 3 columns
  - Dependent Variable (y): Selected (Yes/No)

- **Real Meaning in this notebook**
  - `X = dataset.iloc[:, :-1].values` -> last column kakunda migatha columns anni inputs.
  - `y = dataset.iloc[:, -1].values` -> last column target result.

Simple ga: `X` questions, `y` answer.
Model pani: `X` chusi `y` predict cheyyadam.

In [38]:
# Step 4: 'Data.csv' file nundi complete dataset ni DataFrame lo load chestunnam.
dataset = pd.read_csv('Data.csv')
# Step 5: Last column ni vadilesi migilina columns anni features (X) ga tiskuntunnam.
X = dataset.iloc[:, :-1].values
# Step 6: Last column ni target/dependent variable (y) ga store chestunnam.
y = dataset.iloc[:, -1].values

In [39]:
# Step 7: Features matrix (X) current state ni check cheyyadaniki print chestunnam.
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [40]:
# Step 8: Target vector (y) values correct ga vachaya ani verify cheyyadaniki print chestunnam.
print(y)

<ArrowStringArray>
['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 10, dtype: str


## Taking care of missing data

### Why We Handle Missing Data

- Missing values problem enti?
  Konni rows lo age/salary empty untayi. Model ki empty value ardham kaadu.
- Mean strategy enduku?
  Numeric columns ki average value reasonable fill. Data pattern ni complete ga spoil cheyyakunda fill chestundi.
- `fit` and `transform` difference enti?
  `fit` = average value nerchukuntundi.
  `transform` = aa average ni missing places lo fill chestundi.
- 1:3 columns enduku?
  Ee dataset structure prakaram missing numeric values aa columns lo unnayi.

Simple ga: notebook lo blank spaces ni sensible words tho fill chesinattu.

In [41]:
# Step 9: Missing values fill cheyyadaniki sklearn nundi SimpleImputer ni import chestunnam.
from sklearn.impute import SimpleImputer as si
# Step 10: NaN values ni mean tho replace cheyyadaniki imputer object create chestunnam.
imputer = si(missing_values=np.nan, strategy='mean')
# Step 11: Column index 1 to 2 data meeda mean values learn cheyyadaniki fit chestunnam.
imputer.fit(X[:, 1:3])
# Step 12: Learned mean values use chesi missing places ni fill chestunnam.
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [42]:
# Step 13: Missing data handle ayyaka updated features (X) ni print chesi check chestunnam.
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding Topics in Correct Learning Order

#### 1) What is Category and Categorical Data?
- **Category** ante oka group name or label.
- Example: `France`, `Spain`, `Germany` each one is a category.
- `Yes`, `No` kuda categories.

- **Categorical data** ante text/label form lo unna data.
- Direct ga math cheyyalem, kabatti model ki before processing convert cheyyali.

In our notebook:
1. `Country` column in `X` is categorical (France, Spain, Germany).
2. `Purchased` column in `y` is categorical (Yes, No).

#### 2) Why Encoding is Needed
- ML models mostly numeric calculations chestayi.
- Text values ni model direct ga understand cheyyadu.
- So, text categories ni numbers ga marchadam mandatory.

#### 3) What is One-Hot Encoding?
- One-Hot Encoding ante oka categorical column ni multiple binary (0/1) columns ga split cheyyadam.
- Prati category ki oka separate column untundi.
- Row lo unna category ki `1`, migatha categories ki `0` untayi.

Example (`Country`):
- France -> [1, 0, 0]
- Spain -> [0, 1, 0]
- Germany -> [0, 0, 1]

Why useful?
- Artificial ranking problem avoid avuthundi.
- France=0, Spain=1, Germany=2 ani direct numbers iste model wrong order ni assume cheyyachu.

#### 4) Encoding for Independent Variables (`X`)
- `Country` laanti input categories ki mostly **One-Hot Encoding** use chestam.
- Enduku?
  France=0, Spain=1, Germany=2 ani direct numbers iste model wrong order assume cheyyachu.
- One-hot lo separate columns create avuthayi:
  - France -> [1, 0, 0]
  - Spain -> [0, 1, 0]
  - Germany -> [0, 0, 1]

#### 5) Why `X = np.array(ct.fit_transform(X))`?
- `ct.fit_transform(X)` output numpy-like structure or sparse matrix laga ravachu (encoder settings batti).
- `np.array(...)` valla output ni plain NumPy array format lo stabilize chestam.
- Next preprocessing steps (`train_test_split`, scaling, slicing, printing) consistent ga easy ga work avvadaniki idi help chestundi.
- Simple ga: data ni one standard shape/type lo petti pipeline smooth ga run avvadam kosam.

#### 6) What is LabelEncoder?
- LabelEncoder ane tool text labels ni numeric labels ga convert chestundi.
- Example: `No` -> 0, `Yes` -> 1.
- Idi mostly target/dependent variable (`y`) ki use chestam, especially binary classes unnapudu.

#### 7) Why mostly LabelEncoder is used for dependent variable (`y`)?
- `y` usually final output label kabatti single column lo untundi (Yes/No, Pass/Fail, Spam/Not Spam).
- Ee label ni numeric ga marchadam chalu; class order meaning create cheyyalsina avasaram usually undadu.
- `X` lo categories ki direct 0,1,2 petthe artificial order problem vastundi, kabatti akkada One-Hot safer.
- Example:
  - `y`: Yes/No -> `1/0` (safe)
  - `X` Country: France/Spain/Germany -> 0/1/2 (unsafe), One-Hot better.
- Exception: `X` lo real order unte (Small < Medium < Large), appudu ordinal style encoding use cheyyachu.

#### 8) Encoding for Dependent Variable (`y`)
- `Purchased` laanti target binary values ki **Label Encoding** saripothundi.
- **LabelEncoder enduku use chestam?**
  Model ki final target text (`Yes`/`No`) direct ga ivvakunda numeric labels (`1`/`0`) ga marchadaniki.
- Binary target lo idi simple and correct mapping istundi.
- Example:
  - No -> 0
  - Yes -> 1

#### 9) Quick Rule
1. Input feature category order lekapothe -> One-Hot.
2. Target binary aithe -> Label Encoding enough.
3. Goal: model confusion lekunda clean numeric representation ivvadam.

### Encoding the Independent Variable

In [43]:
# Step 14: Specific columns ki different transforms apply cheyyadaniki ColumnTransformer ni import chestunnam.
from sklearn.compose import ColumnTransformer
# Step 15: Categorical text ni binary columns ga marchadaniki OneHotEncoder ni import chestunnam.
from sklearn.preprocessing import OneHotEncoder
# Step 16: 0th column ki one-hot encoding apply chesi, migatha columns ni alane pass-through cheyyadaniki transformer set chestunnam.
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# Step 17: Transformer output ni fit-transform chesi, next steps lo stable ga use cheyyadaniki plain NumPy array ga convert chestunnam.
X = np.array(ct.fit_transform(X))

In [44]:
# Step 18: Independent variable encoding tarvata X ela undho print chesi verify chestunnam.
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [45]:
# Step 19: Target labels ni number format lo ki marchadaniki LabelEncoder ni import chestunnam.
from sklearn.preprocessing import LabelEncoder
# Step 20: Label encoding operation kosam encoder object create chestunnam (text target ni model-friendly numbers ga marchadaniki).
le = LabelEncoder()
# Step 21: y lo unna class names ni integer labels ga convert chestunnam (example: No->0, Yes->1).
y = le.fit_transform(y)

In [46]:
# Step 22: Dependent variable encoding result ni print chesi confirm chestunnam.
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

### Why We Split into Train and Test

- Train set enduku?
  Model ni nerpinchadaniki.
- Test set enduku?
  Model real ga new data meeda ela perform chestundo check cheyyadaniki.

Simple ga: tuition class (train) and final exam (test) separate chestunnam.

### `test_size` ante enti? (detail)

- Total data lo entha % test ki pettalo cheppe value.
- `test_size=0.2` ante 20% test ki, migilina 80% train ki.
- Value 0 and 1 madhya untundi (0.2 = 20%, 0.25 = 25%).
- Integer kuda ivvachu: `test_size=50` ante exactly 50 rows test ki.

Example:
- Total 100 rows, `test_size=0.2` -> Train = 80 rows, Test = 20 rows.
- Total 100 rows, `test_size=0.3` -> Train = 70 rows, Test = 30 rows.

Endhuku 0.2 (20%) common?
- Test chala chinnaga unte (e.g. 5%) -> exam score meeda nammakam thakkuva (too few samples).
- Test chala peddaga unte (e.g. 50%) -> model ki nerchukovadaniki data thakkuva.
- 20% balanced choice: enough train + enough test.

### `random_state` ante enti? (detail)

- `train_test_split` rows ni randomly shuffle chesi split chestundi.
- `random_state` aa randomness ki oka **fixed seed** istundi.
- Same seed pettinappudu shuffle same order lo jarigi, **same split** malli malli vastundi (reproducibility).

`random_state` LEKUNTE emavutundi?
- Prathi run ki different rows train/test ki veltayi.
- Accuracy koncham up/down avtundi, results compare cheyyadam kashtam.

`random_state` PETTINAPPUDU:
- `random_state=1` today run chesina, repu run chesina -> exactly same X_train, X_test.
- Team lo evaru run chesina same result -> debugging and comparison easy.

Example:
```python
# random_state lekunda -> prathi sari veru split
train_test_split(X, y, test_size=0.2)

# random_state=1 -> anni run lalo same split
train_test_split(X, y, test_size=0.2, random_state=1)

# random_state=42 -> idi kuda fixed, kani 1 kanna veru split
train_test_split(X, y, test_size=0.2, random_state=42)
```

Gurthu pettuko:
- `random_state` value (1 aina, 42 aina) result quality ni marchadu; adi just "which fixed shuffle" ane point.
- Main goal: reproducibility (same result malli ravadam).

Simple ga: cards ni shuffle cheyyadam laantidi. `random_state` ante "same shuffle pattern" ni lock cheyyadam -> prathi sari same order.

In [47]:
# Step 23: Dataset ni train and test sets ga split cheyyadaniki function ni import chestunnam.
from sklearn.model_selection import train_test_split
# Step 24: 80% data training ki, 20% data testing ki split chestunnam; random_state fixed kabatti same split repeat avutundi.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [48]:
# Step 25: Training features ela unnayo choodadaniki X_train ni print chestunnam.
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [49]:
# Step 26: Testing features ela unnayo verify cheyyadaniki X_test ni print chestunnam.
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [50]:
# Step 27: Training target labels ni check cheyyadaniki y_train ni print chestunnam.
print(y_train)

[0 1 0 0 1 1 0 1]


In [51]:
# Step 28: Testing target labels ni check cheyyadaniki y_test ni print chestunnam.
print(y_test)

[0 1]


## Feature Scaling

### Why We Do Feature Scaling

- Scaling problem enti?
  Age 20-50 range lo untundi, salary 30000-90000 range lo untundi. Pedda number column model decision ni dominate cheyyachu.
- StandardScaler enduku?
  Features ni similar scale ki teesukostundi (mean around 0, std around 1).
  Formula concept: z = (x - mean) / std.
- `fit_transform(X_train)` and `transform(X_test)` enduku?
  Train data nundi mathrame mean/std nerchukovali.
  Test data ni ade rules tho transform cheyyali.
  Test data nundi learn chesthe data leakage jaruguthundi.

Simple ga: oka player cm lo, inko player inches lo measure chesthe compare kashtam. First same unit lo ki marchi compare chestunnam.

### Why Feature Scaling AFTER Train-Test Split?

- Test set ante future/new data laanti di. Real world lo aa data mundu manaki teliyadu.
- Scaling ki kavalsina mean and std **only train data** nundi nerchukovali.
- Split **before** scaling chesthe, test data values scaler nerchukune step lo kalavavu.
- Split **after** scaling chesthe, test data mean/std kuda scaler lo kalisipothundi -> **data leakage**.
- Data leakage valla test score falsely high vastundi, kani real new data meeda model fail avvachu.

Correct order:
1. Split cheyyi (train, test).
2. `sc.fit_transform(X_train)` -> train nundi mean/std nerchuko + scale.
3. `sc.transform(X_test)` -> ade learned values tho test ni scale cheyyi.

Simple ga: exam ki mundu question paper chudakunda prepare avvali. Scaler ki test data mundu chupisthe adi "cheating" (leakage) laanti di.

### Standardisation vs Normalisation — Eppudu Edi Vadali?

**Standardisation (StandardScaler)**
- Formula: z = (x - mean) / std.
- Result: mean around 0, std around 1. Range fix kaadu (values negative kuda ravachu).
- Eppudu vadali?
  - Data roughly **normal (bell curve)** ga unnappudu.
  - Outliers unnappudu (normalisation kanna better handle chestundi).
  - Algorithms: Linear/Logistic Regression, SVM, PCA, KNN, Neural Networks — most common default.

**Normalisation (MinMaxScaler)**
- Formula: x_scaled = (x - min) / (max - min).
- Result: anni values **0 and 1 madhya** (fixed range).
- Eppudu vadali?
  - Data distribution normal kaadu (unknown/skewed) unnappudu.
  - Fixed bounded range [0,1] kavali anapp (e.g. image pixels 0-255 -> 0-1).
  - Algorithms: Neural Networks (bounded input), KNN, distance-based models.
- Jagratha: outliers unte min/max ni cheddaga effect chestai (adi bad).

**Quick Rule:**
- Confusion unte -> **Standardisation** (safe default, ekkuva cases lo pani chestundi).
- Bounded [0,1] range kavali OR data normal kaadu -> **Normalisation**.
- Tree-based models (Decision Tree, Random Forest, XGBoost) ki scaling **avasaram ledu**.

Simple ga:
- Standardisation = "average nunchi entha door" ani cheppadam (center 0).
- Normalisation = "0 to 100 marks percentage laaga" 0-1 loki teesukuravadam.

### Ee Techniques Enduku Apply Chestam? (kid ki cheppinatlu)

Oohinchuko: nuvvu class teacher vi. Oka student Ravi undi.
- Ravi height **150 cm**.
- Ravi weight **45 kg**.

Ippudu neeku oka "friend robot" (model) undi. Aa robot students ni compare cheyyadaniki numbers chusthundi. Kaani robot ki oka chinna problem undi: **pedda number ekkuva important** ani anukuntundi.

- Height number = 150 (pedda).
- Weight number = 45 (chinna).

Robot ki telavadu ivi different things (cm and kg) ani. Adi anukuntundi "150 anni 45 kanna chala ekkuva, kabatti height matrame important" — idi **tappu**. Nijaniki rendu equal ga important.

**Ee problem ni fix cheyyadaniki manam scaling techniques vadatam.** Manam anni numbers ni oka **same/fair scale** loki marchi, robot ki cheptam: "ee rendu columns ni equal ga chudu."

**Enduku idi mukhyam? (3 chinna reasons)**
1. **Fairness:** Pedda number unna column (salary laaga) chinna number column (age laaga) ni dominate cheyyakunda apthundi. Anni features ki equal chance.
2. **Speed:** Chala models (gradient descent vadedi) same-scale data meeda **fast** ga nerchukuntai. Different scales unte slow and confusing.
3. **Accuracy:** Distance calculate chese models (KNN, SVM) ki scaling lekapothe answers tappu vastai, endukante pedda number distance ni control chestundi.

**Ilaanti daily-life example:**
Race petta: oka pillodini **kilometers** lo, inko pillodini **meters** lo speed cheppi "evadu fast?" ani adigithe confuse avtam. First rendu ni **same unit** loki marchi, aa tarvata compare chestam. Scaling chesedi exactly ade — anni ni same "language/unit" loki marchi model ki compare cheyyadam easy chestundi.

**Chinna gurthu (summary):**
- Scaling = numbers ni fair ga, same size loki marchadam.
- Standardisation and Normalisation = ade pani chese rendu different methods.
- Idi model ki nerchukovadam **easy, fast, and fair** chestundi.

In [52]:
# Step 29: Feature values ni same scale lo ki teesukoradaniki StandardScaler ni import chestunnam.
from sklearn.preprocessing import StandardScaler
# Step 30: Scaling operation kosam scaler object create chestunnam.
sc = StandardScaler()
# Step 31: Training data meeda mean and std learn chesi X_train ni scale chestunnam.
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
# Step 32: Ade learned scaling rules ni X_test ki apply chestunnam (data leakage avoid avuthundi).
X_test[:,3:] = sc.transform(X_test[:,3:])

### Feature Scaling Code Explanation (Line by Line)

Ee code lo `X_train[:,3:]` and `X_test[:,3:]` ane slicing use chesam. Adi enduku ane point chala important.

Mundu oka gurthu: One-Hot Encoding tarvata mana `X` lo modati konni columns dummy (0/1) columns ayyayi.
- Column 0, 1, 2 -> Country one-hot columns (France, Spain, Germany laanti 0/1 values).
- Column 3 -> Age.
- Column 4 -> Salary.

#### `[:, 3:]` ante enti?
- NumPy slicing format: `[rows, columns]`.
- `:` ante anni rows teesuko.
- `3:` ante column index 3 nunchi last varaku teesuko (0,1,2 vadilesi).
- Ante manam Age and Salary columns matrame select chestunnam.

#### Line 1: `from sklearn.preprocessing import StandardScaler`
- StandardScaler tool import chestunnam. Idi numbers ni standardise chestundi (mean 0, std 1).

#### Line 2: `sc = StandardScaler()`
- Oka scaler object (`sc`) create chestunnam. Idi mean and std store chesukoni scaling chestundi.

#### Line 3: `X_train[:,3:] = sc.fit_transform(X_train[:,3:])`
- `fit_transform` rendu panulu chestundi:
  - fit -> X_train lo Age and Salary columns nunchi mean and std nerchukuntundi.
  - transform -> aa learned values tho aa columns ni scale chestundi.
- Result ni malli ade columns lo (`X_train[:,3:]`) tirigi pettestunnam.
- Dummy columns (0,1,2) ni touch cheyyatam ledu, avi already 0/1 kabatti scaling avasaram ledu.

#### Line 4: `X_test[:,3:] = sc.transform(X_test[:,3:])`
- Ikkada transform only (fit kaadu).
- X_train nunchi already nerchukunna same mean/std ni X_test ki apply chestunnam.
- Idi data leakage avoid chestundi (test data nunchi kotha mean/std nerchukokudadu).

#### Enduku `[:, 3:]` full `X_train` kaadu?
- One-hot dummy columns (0,1,2) already 0/1 values.
- Vaatini scale chesthe:
  - Vaati meaning (which category) paadi potundi.
  - 0/1 values negative decimals ga maratayi, interpret cheyyadam kashtam.
- Anduke only real numeric columns (Age, Salary) ni scale chestunnam, dummy columns ni alane vadilestunnam.

#### Chinna summary
- `[:, 3:]` ante "dummy columns vadilesi, real numbers (Age, Salary) matrame scale cheyyi."
- `fit_transform` train meeda, `transform` test meeda -> fair and leakage-free scaling.

In [53]:
# Step 33: Scaled training features ni print chesi centered values vachaya ani check chestunnam.
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [55]:
# Step 34: Scaled testing features ni print chesi final preprocessing output ni verify chestunnam.
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]


## Kid-Style Architecture and Flow (Data Preprocessing)

Manam ikada raw data ni clean chesi, machine learning ki ready chestunnam.
Simple ga idi "school ki velladaniki child ni ready cheyyadam" laanti process.

### End-to-End Flow

```mermaid
flowchart TD
    A[Raw CSV Data] --> B[Load into Pandas]
    B --> C[Split X and y]
    C --> D[Handle Missing Values]
    D --> E[Encode Categorical Values]
    E --> F[Train Test Split]
    F --> G[Feature Scaling]
    G --> H[Clean ML Ready Data]
```

### Architecture Simple Explanation
1. **Input Layer**: `Data.csv` nundi raw data vasthundi.
2. **Cleaning Layer**: missing values fill chestham.
3. **Encoding Layer**: text values ni numbers ga marchestham.
4. **Split Layer**: train set and test set create chestham.
5. **Scaling Layer**: feature values same scale lo ki teesukostham.
6. **Output Layer**: model training ki ready data.

### Kid Analogy
- Raw data = unwashed vegetables
- Cleaning = wash + cut
- Encoding = labels pettadam
- Split = practice vs exam papers
- Scaling = all rulers ni same unit lo set cheyyadam